export CUDA_VISIBLE_DEVICES=0
python3 main.py \
--epoch 25 \
--learning_rate .0001 \
--beta 0.5 \
--batch_size 128 \
--sample_size 64 \
--input_height 28 \
--output_height 28 \
--lambda_val 1.0 \
--smoothing 1.0 \
--use_resize True \
--dataset mnist \
--input_fname_pattern */*.jpg \
--checkpoint_dir checkpoint \
--sample_dir samples \
--crop False \
--visualize False \
--can False \
--use_s3 False \
--s3_bucket mlberkeley-cans \
--replay True \
--train
